[features]
seeds = false
[programs.devnet]
pzportal = "CYAiXdNguaSdW43pQNqcmdHQiUbFNfteGCAiSre7NTJo"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/kipland/.config/solana/id.json"

[scripts]
test = "node tests/pzportal.js"
