[features]
seeds = false
[programs.localnet]
pzportal = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/kipland/.config/solana/id.json"

[scripts]
test = "node tests/pzportal.js"
